# Generated by Django 5.2.8 on 2025-11-10 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occasions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='occasions.occasion')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-reserved_at'],
                'unique_together': {('occasion', 'attendee')},
            },
        ),
    ]
